# Generated by Django 4.2.1 on 2023-05-15 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False, verbose_name='idTargeta')),
                ('nombre', models.CharField(max_length=16)),
                ('dinero', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='correo')),
                ('user', models.CharField(max_length=255, verbose_name='usuarios')),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idTransaccion')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(max_length=10)),
                ('estado', models.CharField(default='esperando', max_length=32, verbose_name='estado')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paysystem.usuario')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='paysystem.tarjeta', verbose_name='transacciones')),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='paysystem.usuario', verbose_name='tarjetas'),
        ),
    ]
