# Generated by Django 4.2.1 on 2023-05-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paysystem', '0002_tarjeta_usuario_transaccion_tarjeta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='tarjeta',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='user',
            field=models.ForeignKey(default='defaultUser', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='paysystem.usuario', verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dinero',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
